insert into main.ChrClasses (id, damage_bonus_stat, display_power, pet_name_token, name_lang_en_gb, name_lang_ko_kr, name_lang_fr_fr, name_lang_de_de, name_lang_en_cn, name_lang_en_tw, name_lang_es_es, name_lang_es_mx, name_lang_ru_ru, name_lang_ja_jp, name_lang_pt_pt, name_lang_it_it, name_lang_unknown_12, name_lang_unknown_13, name_lang_unknown_14, name_lang_unknown_15, name_lang_flags, name_female_lang_en_gb, name_female_lang_ko_kr, name_female_lang_fr_fr, name_female_lang_de_de, name_female_lang_en_cn, name_female_lang_en_tw, name_female_lang_es_es, name_female_lang_es_mx, name_female_lang_ru_ru, name_female_lang_ja_jp, name_female_lang_pt_pt, name_female_lang_it_it, name_female_lang_unknown_12, name_female_lang_unknown_13, name_female_lang_unknown_14, name_female_lang_unknown_15, name_female_lang_flags, name_male_lang_en_gb, name_male_lang_ko_kr, name_male_lang_fr_fr, name_male_lang_de_de, name_male_lang_en_cn, name_male_lang_en_tw, name_male_lang_es_es, name_male_lang_es_mx, name_male_lang_ru_ru, name_male_lang_ja_jp, name_male_lang_pt_pt, name_male_lang_it_it, name_male_lang_unknown_12, name_male_lang_unknown_13, name_male_lang_unknown_14, name_male_lang_unknown_15, name_male_lang_flags, filename, spell_class_set, flags, cinematic_sequence_id, required_expansion)
values  (1, 0, 6, 'PET', 'Warrior', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712191, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712172, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712172, 'WARRIOR', 4, 50, 0, 0),
        (2, 0, 6, 'PET', 'Paladin', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712191, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712172, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712172, 'PALADIN', 10, 58, 0, 0),
        (3, 1, 6, 'PET', 'Hunter', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712191, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712172, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712172, 'HUNTER', 9, 22, 0, 0),
        (4, 1, 6, 'PET', 'Rogue', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712191, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712172, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712172, 'ROGUE', 8, 2, 0, 0),
        (5, 0, 6, 'PET', 'Priest', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712191, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712172, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712172, 'PRIEST', 6, 2, 0, 0),
        (6, 9, 6, 'PET', 'Death Knight', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712172, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712172, 'DEATHKNIGHT', 15, 122, 165, 2),
        (7, 1, 6, 'PET', 'Shaman', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712191, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712172, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712172, 'SHAMAN', 11, 26, 0, 0),
        (8, 0, 6, 'PET', 'Mage', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712191, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712172, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712172, 'MAGE', 3, 2, 0, 0),
        (9, 0, 6, 'DEMON', 'Warlock', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712191, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712172, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712172, 'WARLOCK', 5, 6, 0, 0),
        (11, 0, 6, 'PET', 'Druid', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712191, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712172, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712172, 'DRUID', 7, 10, 0, 0);